# Generated by Django 5.0 on 2025-06-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='attachment',
            name='url',
            field=models.URLField(blank=True, help_text='External URL if file is hosted elsewhere', max_length=500),
        ),
    ]
