# Generated by Django 5.0 on 2025-06-22 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(help_text='Unique certificate identifier', max_length=50, unique=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, help_text='Token for certificate verification', unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateField()),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text='Final course score percentage', max_digits=5, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
