# Generated by Django 5.0 on 2025-06-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('exam', 'Exam')], default='quiz', max_length=20)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('passing_score', models.PositiveIntegerField(default=70)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['course', 'lesson', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('time_spent_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assessment Attempt',
                'verbose_name_plural': 'Assessment Attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
