# Generated by Django 5.0 on 2025-06-22 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0002_attachment_name_attachment_url'),
        ('courses', '0001_initial'),
        ('posts', '0003_post_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated completion time in minutes', null=True)),
                ('content_post', models.OneToOneField(blank=True, help_text="Post with post_type='lesson' for lesson content", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='posts.post')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_videos', to='attachments.attachment')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'slug')},
            },
        ),
    ]
